###############################################################################
# General Configuration
###############################################################################
version: 4.0.{build}

###############################################################################
# Environment Configuration
###############################################################################
image: Visual Studio 2019

configuration: 
  - Release
  - Debug
platform: 
  - x64
  - x86
environment:
  matrix:
  - solution_name: ../IDE/VS/Timing.sln

###############################################################################
# Build Configuration
###############################################################################
build:
  parallel: true
  verbosity: normal

build_script:
  - msbuild %solution_name%